Импорт nympy, примеры создания массивов

In [40]:
import numpy as np

x = np.arange(10)
y = np.zeros(5)
z = np.ones(5)
a = np.array([[1,2], [4, 6]])

Деманстрация .shape .dtype

In [41]:
print(a.shape)  # Вывод: (2, 3, 1)
print(a.dtype)

(2, 2)
int64


Примеры векторных операций и базовых статистик

In [43]:
b = np.array([[4, 6], [2, 5]])
c = a+b
c


array([[ 5,  8],
       [ 6, 11]])

In [44]:
c = a*b
c

array([[ 4, 12],
       [ 8, 30]])

In [45]:
np.cos(a)

array([[ 0.54030231, -0.41614684],
       [-0.65364362,  0.96017029]])

In [46]:
np.sum(a)

np.int64(13)

In [47]:
a.max()

np.int64(6)

In [49]:
a.max(axis=0)

array([4, 6])

Пример индексирования и срезов 

In [51]:
c = np.array([1,2,3,4,5,6,7,8,9,10])
c[[3,5]]

array([4, 6])

In [52]:
c[3:5]

array([4, 5])

In [53]:
c[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [54]:
c[2:8:2]

array([3, 5, 7])